org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.20
forge_version_range=[47.4.20,48)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

mod_id=meplacementtool
mod_name=ME Placement Tool for gto
mod_archive_name=ME-Placement-Tool-for-gto
mod_version=2.1.4-for-gtocore-0.5.6-beta
mod_license=LGPL-3.0-only
mod_group_id=com.moakiee
mod_authors=moakiee, CystrySU, _leng, Futureism, ChatGPT
mod_description=ME Placement Tool adapted for GregTech Odyssey and its customized Applied Energistics 2 runtime.
